# Generated by Django 4.2.6 on 2023-10-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_main_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
