# Generated by Django 4.2.6 on 2023-10-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_church_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='church_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
