# Generated by Django 4.2.6 on 2023-10-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetindividual',
            name='arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patnershiparm'),
        ),
    ]
