# Generated by Django 4.2.6 on 2023-10-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_targetchurch_target_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetchurch',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'monthly'), (2, 'yearly'), (3, 'quarterly')], null=True),
        ),
    ]
