# Generated by Django 4.2.6 on 2023-10-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_targetindividual_target_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetindividual',
            name='frequency',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'monthly'), (2, 'yearly'), (3, 'quarterly')], null=True),
        ),
    ]
