# Generated by Django 4.2.6 on 2023-10-14 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=255)),
                ('main_target', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date_payed', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.individual')),
            ],
        ),
        migrations.CreateModel(
            name='TargetChurch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_frequent', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('frequency', models.PositiveIntegerField(choices=[(1, 'monthly'), (2, 'yearly'), (3, 'quarterly')], null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('passed_time', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.church')),
            ],
        ),
        migrations.CreateModel(
            name='TargetIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_frequent', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_date', models.DateField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('frequency', models.PositiveIntegerField(choices=[(1, 'monthly'), (2, 'yearly'), (3, 'quarterly')], null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('passed_time', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.individual')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'church'), (2, 'individual')], default=1),
        ),
        migrations.DeleteModel(
            name='ChurchTarget',
        ),
        migrations.AddField(
            model_name='church',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
