# Generated by Django 4.2.6 on 2023-10-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_targetindividual_arm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetchurch',
            name='target_date',
        ),
    ]
