# Generated by Django 4.2.6 on 2023-10-19 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_targetchurch_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetindividual',
            name='target_date',
        ),
        migrations.AlterField(
            model_name='targetindividual',
            name='arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.patnershiparm'),
        ),
        migrations.AlterField(
            model_name='targetindividual',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetindividual',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
