# Generated by Django 4.2.6 on 2023-10-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_church_church_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetchurch',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetchurch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
