# Generated by Django 4.2.6 on 2023-11-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_targetchurch_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.church'),
        ),
    ]
